# netlify.toml — Astro + GA4 lazy (sans inline) + headers sécurité

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# -----------------------------------------
# HEADERS GLOBAUX
# -----------------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://region1.analytics.google.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; base-uri 'self'; frame-ancestors 'self'; upgrade-insecure-requests"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Cross-Origin-Opener-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

# -----------------------------------------
# HEADERS SPÉCIFIQUES /audio/*
# -----------------------------------------
[[headers]]
  for = "/audio/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://phdefoy.com"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"


[[headers]]
  for = "/protected/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    # Content-Disposition = "attachment;
   
[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/fonts/*.woff"
  [headers.values]
    Content-Type = "font/woff"

---
title: ""
pubDate: " 2025"
heroImageLink: "https://www.amazon.com/dp/B0G5MVCT7B"
heroImage: "/images/ia/manuel-apprentissage-le-russe-pour-les-débutants-niveau-a2-auteur-philippe-de-foy/manuel-apprentissage-le-russe-pour-les-débutants-niveau-a2-auteur-philippe-de-foy.png" 
tags: ["Russe"]
---